# -*- coding:utf-8 -*-
from datetime import datetime
from odoo import fields, models, api, _
from odoo.exceptions import ValidationError
from odoo.tools.safe_eval import safe_eval

import calendar


class HrVersion(models.Model):
    _inherit = 'hr.version'

    is_pt_company = fields.Boolean(compute='_compute_is_pt_company', store=False)

    christmas = fields.Selection([('sem_dist', 'Without Distribution'), ('com_dist_metade', u'1/2 in twelfths'),
                                  ('com_dist_total', u'Totality in twelfths')],
                                 string='Christmas', required=False,
                                 help=u"Distribution of the Christmas allowance in twelfths, or not.", tracking=True)
    vacation = fields.Selection([('sem_dist', 'Without Distribution'), ('com_dist_metade', u'1/2 in twelfths'),
                                 ('com_dist_total', u'Totality in twelfths')],
                                string='Vacation', required=False,
                                help=u"Distribution of the Vacation allowance in twelfths, or not.", tracking=True)
    food = fields.Selection([('normal', 'Normal'), ('cartao', u'In card')],
                            string=u'Meal', required=False,
                            help=u"Distribution of meal allowance.", tracking=True)
    foodValue = fields.Monetary(string=u'Daily Meal Allowance', required=False,
                                default=lambda self: self.env.company.default_hr_payroll_food_val,
                                help=u"Daily value of the meal allowance.", tracking=True,
                                currency_field='currency_id')

    km_value = fields.Monetary(string=u"KM Unit Value", required=False,
                               default=lambda self: self.env.company.default_hr_payroll_km_val,
                               help=u"Unit value per km", tracking=True,
                               currency_field='currency_id')
    ss_regime = fields.Many2one('ss.regime', string='Social Security Regime',
                                help=u"Social Security Regime.", tracking=True)
    payment = fields.Selection(
        [('numerario', u'Cash'), ('transferencia_bancaria', u'Bank Transfer'), ('cheque', u'Check')],
        string='Payment Method', required=False,
        help=u"Means of payment for the due date generated by this contract.", tracking=True)
    hourlyCost = fields.Monetary(string=u'Value / Hour', required=False,
                                 help=u"Employee hourly rate.", tracking=True,
                                 currency_field='currency_id')
    # subcontractorIRSRetentionTax = fields.Float(string=u'Withholding Rate at Source', required=False,
    #                              help=u"Withholding Tax (Subcontractors).")
    exemption_schedule = fields.Boolean(default=False, help=u"Does the employee have an exemption from working hours?",
                                        tracking=True)

    seniority_payments = fields.Monetary(string="Seniority Payments", required=False,
                                         help="Seniority Payments", tracking=True,
                                         currency_field='currency_id')

    MONTHS = [(str(month).zfill(2), month_name) for month, month_name in enumerate(calendar.month_name) if month != 0]
    MONTH_SELECTION = MONTHS + [('paid_separately', 'Paid Separately')]

    month_selection_vac = fields.Selection(MONTH_SELECTION, string='Month for Vacation Allowance', tracking=True)
    month_selection_chr = fields.Selection(MONTH_SELECTION, string='Month for Christmas Allowance', tracking=True)

    fail_allow_amount = fields.Monetary(string="Fail Allow Amount", tracking=True,
                                        currency_field='currency_id')

    cost_allw_amount = fields.Monetary(string="Cost Allowance Amount",
                                       default=lambda self: self.env.company.default_hr_payroll_cost_allowance_daily_val,
                                       tracking=True,
                                       currency_field='currency_id')

    cost_allw_amount_foreign = fields.Monetary(string="Foreign Cost Allowance Amount",
                                               default=lambda self: self.env.company.default_hr_payroll_foreign_cost_allowance_daily_val,
                                               tracking=True,
                                               currency_field='currency_id')

    has_fail_allow = fields.Boolean(default=False, tracking=True)

    standard_calendar_id = fields.Many2one(
        'resource.calendar', default=lambda self: self.env.company.resource_calendar_id, readonly=False,
        domain="['|', ('company_id', '=', False), ('company_id', '=', company_id)]", tracking=True)

    exemption_schedule_percentage = fields.Float(default=lambda self: self.env.company.exemption_schedule_percentage,
                                                 tracking=True)

    night_work_percentage = fields.Float(default=lambda self: self.env.company.night_work_percentage, tracking=True)

    youth_irs = fields.Boolean(string="Youth IRS", default=False, tracking=True)

    income_years_declared = fields.Selection([
        ('1', 'First Year'),
        ('0.75', 'Second to Fourth Year'),
        ('0.5', 'Fifth to Seventh Year'),
        ('0.25', 'Eighth to Tenth Year')
    ])

    @api.depends('company_id', 'company_id.country_id')
    def _compute_is_pt_company(self):
        for rec in self:
            rec.is_pt_company = rec.company_id.country_id.code == 'PT' if rec.company_id and rec.company_id.country_id else False

    def _generate_work_entries(self, date_start, date_stop, force=False):
        date_start_datetime = datetime.combine(fields.Datetime.to_datetime(date_start), datetime.min.time())
        date_stop_datetime = datetime.combine(fields.Datetime.to_datetime(date_stop), datetime.max.time())
        return super()._generate_work_entries(date_start_datetime, date_stop_datetime, force)

    def imprimir(self, val):
        print(val)

    def make_eval(self, val):
        return safe_eval(val)
