<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:fest="http://www.gep.msess.gov.pt/sguri/ru/anexo_fest"
           xmlns:t="http://www.gep.msess.gov.pt/sguri/tipos_comuns"
           xmlns="http://www.gep.msess.gov.pt/sguri/ru"
           targetNamespace="http://www.gep.msess.gov.pt/sguri/ru"
           elementFormDefault="qualified"
           version="3.2.13">
    <xs:import namespace="http://www.gep.msess.gov.pt/sguri/ru/anexo_fest" schemaLocation="anexo-fest-1.3.13.xsd"/>
    <xs:import namespace="http://www.gep.msess.gov.pt/sguri/tipos_comuns" schemaLocation="tipos-comuns-1.3.13.xsd"/>
    <xs:element name="relatorio_unico" type="relatorio_unicoType"/>
    <xs:complexType name="relatorio_unicoType">
        <xs:sequence>
            <xs:element name="header" type="headerType"/>
            <xs:element name="body" type="bodyType"/>
        </xs:sequence>
        <xs:attribute name="XML_DATA" use="required" fixed="3.2.13" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="headerType">
        <xs:sequence>
            <xs:element name="aplicacao" type="aplicacaoType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="aplicacaoType">
        <xs:sequence>
            <xs:element name="nome" type="t:minType"/>
            <xs:element name="versao" type="t:minType"/>
            <xs:element name="empresa" type="t:minType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="bodyType">
        <xs:sequence>
            <xs:element name="anexos" type="anexosType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="anexosType">
        <xs:sequence>
            <xs:element ref="fest:anexo_fest"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>